language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm install --global expo-cli
  - npm test
after-success:
  - npx expo login -u $expo_username -p $expo_password
  - npx expo publish --non-interactive
